version: '3.8'

services:
  db:
    image: mysql:5.7
    platform: linux/amd64
    container_name: wordpress_db
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}

  wordpress:
    image: wordpress:latest
    platform: linux/amd64
    container_name: wordpress_app
    depends_on:
      - db
    volumes:
      - ./wordpress:/var/www/html
      - ./docker/php.ini:/usr/local/etc/php/conf.d/custom.ini
    ports:
      - "8000:80"
    environment:
      WORDPRESS_DB_HOST: wordpress_db:3306
      WORDPRESS_DB_NAME: ${MYSQL_DATABASE}
      WORDPRESS_DB_USER: ${MYSQL_USER}
      WORDPRESS_DB_PASSWORD: ${MYSQL_PASSWORD}

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    platform: linux/amd64
    container_name: wordpress_phpmyadmin
    ports:
      - "8080:80"
    environment:
      PMA_HOST: wordpress_db
      PMA_PORT: 3306
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      UPLOAD_LIMIT: 64M

volumes:
  db_data: